<?php
/*
 * @package jmws_idMyGadget_for_drupal
 *
 * Module Name: idmygadget
 * Module URI:
 * Description: Integrate idMyGadget with a couple of drupal themes (to start).
 * Author: Tom W Hartung
 * Version: 1.0
 * Author URI: http://tomwhartung.com/
 */
define( 'IDMYGADGET_MODULE_DIR', __DIR__ . DIRECTORY_SEPARATOR . 'src/JmwsIdMyGadget' );

/**
 * Add the jquery mobile css and js
 */
function idmygadget_page_attachments_alter(&$page) {
  global $jmwsIdMyGadget;
  //
  // If the $jmwsIdMyGadget global object does not exist, and at one point we were getting that error,
  //   create the service and get it
  // Reference: https://api.drupal.org/api/drupal/core!core.api.php/group/container/8
  //
  if ( ! is_object($jmwsIdMyGadget) ) {
    $idMyGadgetService = \Drupal::service('idmygadget.idmygadget_service');
    $jmwsIdMyGadget = $idMyGadgetService->jmwsIdMyGadget;
  }
  //
  // If we are using jQuery Mobile (based on the value of various admin parameters),
  //   attach the css and js
  // Likewise with the hamburger js file, which would only be needed if jQuery Mobile is
  //
  if ( $jmwsIdMyGadget->usingJQueryMobile ) {
    $page['#attached']['library'][] = 'idmygadget/jquery-mobile';
    // error_log('idmygadget_page_attachments_alter: attaching jQuery Mobile css and js');
    if ( $jmwsIdMyGadget->hamburgerIconLeftOnThisDevice ||
         $jmwsIdMyGadget->hamburgerIconRightOnThisDevice ) {
      $page['#attached']['library'][] = 'idmygadget/hamburger-menu-icon';
      error_log('idmygadget_page_attachments_alter: attaching hamburger-menu-icon js file');
    }
  }
}
