<?php
/*
 * @package jmws_idMyGadget_for_drupal
 *
 * Module Name: idMyGadget
 * Module URI:
 * Description: Integrate idMyGadget with a couple of drupal themes (to start).
 * Author: Tom W Hartung
 * Version: 1.0
 * Author URI: http://tomwhartung.com/
 */
define( 'IDMYGADGET_MODULE_DIR', __DIR__ . DIRECTORY_SEPARATOR . 'src/JmwsIdMyGadget' );
// require_once( 'idMyGadget/JmwsIdMyGadgetDrupal.php' );
// require_once 'jmws_idMyGadget_for_joomla/PhoneBurgerMenuIcon.php';

// print '<p>Hi from jmws_idMyGadget_for_drupal!!</p>';

/**
 * Check the idmygadget object, instantiating it if necessary, and check the installation
 */
$jmwsIdMyGadget = null;
function idMyGadget_page_alter( &$page ) {
  global $jmwsIdMyGadget;

  print '<p>Hi from function idMyGadget_page_alter in idMyGadget.module!!</p>';
}

/**
 * Add the jquery mobile css and js
 */
function idmygadget_page_attachments_alter(&$page) {
  global $jmwsIdMyGadget;
  //
  // If the $jmwsIdMyGadget global object does not exist, create the service and get it
  // Reference: https://api.drupal.org/api/drupal/core!core.api.php/group/container/8
  //
  if ( is_object($jmwsIdMyGadget) ) {
    error_log('idmygadget_page_attachments_alter: global object exists');
  }
  else {
    $idMyGadgetService = \Drupal::service('idmygadget.idmygadget_service');
    $jmwsIdMyGadget = $idMyGadgetService->jmwsIdMyGadget;
    error_log('idmygadget_page_attachments_alter: created the global object wtf');
  }
  //
  // If we are using jQuery Mobile (based on the value of various admin parameters),
  //   attach the css and js
  //
  if ( $jmwsIdMyGadget->usingJQueryMobile ) {
    $page['#attached']['library'][] = 'idmygadget/jquery-mobile';
    error_log('idmygadget_page_attachments_alter: attaching jQuery Mobile css and js');
  }
}
